sudo: required
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script: yarn add polymer-cli
script:
  - xvfb-run wct --module-resolution=node --npm --skip-plugin sauce
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --module-resolution=node --npm --plugin sauce --skip-plugin local; fi'
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET" -in deploy.enc -out deploy_key -d; fi'
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
env:
  global:
    - secure: tRGnvibCU9WJY3lzpyK1zrT6F4lQqpnayuh/YBSCJna7T0tkD3ob/+D91VBeYooDMg+uYf6B/ZoCt8KhXV/4guUysec44cMZ2+ashyj7/4JbImHBtYAMP3cVdTXvk+QZAfhsJ9acIKeERHpoF8fHmxH/bWP/jHBKzZ2QImH3Ss47899nhE7f57c3VbHtsctasqC9S7F/KDN9JVFJN9QtW937amHSE9/gxyL54AfzxpoJuARq/sRO2n1dp7JBbo/DqnMPt8S6VJgOhjJBobqwL9h3v6K2VPG6dkClX3plDvcY6/vNsNqlGdM2LgFLO7W2wzWXKDMqb/3i7CzBbaUE6XNl+0UYf89NicjLY4hFCK0L8cf/bsK8wav0aLQH/k6mb6+Baz7pWex2VZNM5z63voE1t+4DYWozA7wp1UIv2K448qq8uUiuFRvwsmaZrH8chC3UnkZIlYR81Pl3MPDMySRDhwQq17KGToeYV0dmSRaYtCw88+OoGnDOq+7nX2bPgPmsYORzzz+fZlhUk1RS63/Gb/Qzw0hmfBJO2V4nmXXLSb0AHA6ZmSXRxQSjl36JBEyYNGSr4/NoZM9o55tEg0pGgN/rAa63d8FLlRmOro7zmoqIXJkTbuE2Ba0o8AUSBSY5sZpu4Ro1Jji2FAgqX0m4C5oW2HH2DHQ1FSWVnfI=
    - secure: xsldV2X5Xw7FyO4hWuOiUq398Ty72I/4LEzMIHBTkt3l06SozfD5Y3N8SRXCa81DKb5hG4xCBPWxiOxF6i9MS5wVBxF0/dQGKHPqPLasvn4EHumiiau0eHqh82vbkS6uMmjF0d8MZQa/b4BGmmTS3UnbKoXDzgyRo0bsT3vc2F8+eHEoeJcq0rN5Vg/XCPuRSA0GSizA0j4+IPVasOXBtwiMdr6NQOTaBZS2p1EIR94/xuWfksklLycc6MLZ5+PEK4mBCIx8yU7gCLz2Sj9aFoVoaInmD9OYn4yJs5wExRA9IMEWX4XIE3zh6qFRKPFvseBnSEll45787O6QHr+wu01oFucJWLQ9qAhavR8FfqMeAaDAwP6+RBGz5d/gH5erkOWdEM7l2k27iBkwpn4uxZZwIUchM8IbFdvsL0Z7Uyipdj0jM34itN9ojXJMEg0IjRH81BTMsyeozHNOLS8ZVGC57Z4zDfmxdttdyeCPFlfj84FOgiQWGWkvcEIaAr06v2cuSgZRvvXRs/6ovxp4EVmMNPnQkOX3qH3bm10tL4hw33nxzcD718h/mlV8FDxsiFQXEM6nYtpc8pM5NOHzrNbeutmriuRNjYtGH8M/ii+dwbR7BMpO/5Lx28mgOgZbdfdwmadNdG1Qi1xmCQFcvI38VyrA3U1th1o5B87HPRE=
    - secure: hbLBBCvGzzACjt5O61fTMldStmUZlJXP3Ongy/U4jWv5HudOKeyfI+FJMzoDIeaXXfnw5WdocdOlLkvNsH+YKdFMqvVOZHm5xzMnZBh6663rGqLUOSJPfFe0JgbwAcSddXgiAtRrKUe/w518bgOl6sALPurGCh4taS2/MOiLxSQS5XDrrs6vlLBrvy0Q0oisZ0eIM5mStuzzdJrj/0KEy1VE+wD45Qg/fMG1Ws2gCvYpnoukgniO8lFISF+4UNoaN2qYL6Q9ombnc9UzDPmR5yY5l+WJNPwZoHb/e3c9mYpQ6kayeCLnWj6CSzNayatxqFD98WcjzzwicPc/NW2SnCIbwRJgUAYHoLVpGnllFEcu0iMjyHHWzVV0e5R5sSVzu8rSvQoGolYesix04D8/vWGWE5KXZwikxnfQBGQIJmChXDBtdGLb0eXodz0HDh7l0Dbw3vKmYDc1rUTzetr81JZeXt1u8iL3Juy9dmjhE+WGzSZ8I/wtL7Qp2CY21TFjEU/HfhrZIAn3S9mSMCG8AY5rIdb0MBuSS2D/de0HCBY+lfF6x6M2iWLnOOxMw91NJITlketFIxIqMbSTp4GABXMAv4jxKBU0ZQvrFQysffEQJVcFq6Bds0lQgGZUG5tdIutZDnPhiQjJ8L2Yd7Qss7FRoMUOs090nhoyvSu+Exw=
    - secure: I2BqwkkeoEh92oryRo7z9zDhNAOYMSNXI6HrFFKfrC2f08cUFczYeDtjdQVUT6W7xKn4y29HDYSyN6do9v1TyLmQfwjUVApiz4pp4dk6VXft5WWXFZ6JgAt1xEy8uDxWPdX7ngXQNIs4Xe+68yEV2XO/8aLO2U1Tngw/BGMynQ8Q6iFiX6WSFSj1c+bL3z+rFOAVzCmSS84Go9braPb0aNK/un/5NOfV5t3zG7eJkhpSMCMWXBFqg9H6Qu7bjmRVQ8O1EWj9u7em5YenilONvg+ixetsco18TeudaQ1js/9oy3KaYLn+7Isk3hHYBXBmTc9GJFDrKKvQNeZzDFyDqOaydhzTpS6u/pdLCCH6H7NHJ82b/p5CPX8hNXE+ZP0M55+nEvdvxr7fP9i//gQMP2JY11RIdHmEix32eW3jiS0z17U4ZKtJlW7whfzPgKl6715MTklMkjJt6/uvY/ALI/ZCeiflrRdEvWw1NhTiI1WWDyz7cTiWIr07/41DctIkWYPWHeHPY3TUNrcrGmfQENLFTsOY+frzzcaXhZsfvkzZadmxEDveqVRmJEx6wcNxHEGjl3YYpWx6rMx2YDO7SlbUyQxwUUaKQffUQs6Wr0Gde93Cdmiy9VjtVxhVIdEuYy+go3uMeKnB1nzTa6anKaoxRliEFqOAOrLtcimtASc=

